#!/bin/bash

cd ${0%/*} || exit 1 # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

runApplication topoSet

[ ! -d 0 ] && cp -r 0.orig 0

runApplication $(getApplication)


